# version: '3.8'

services:
  db-mongo:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    expose:
      - 27017

  be-nest:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: unless-stopped
    environment:
      - PORT=8080
      - NODE_ENV=production
      - MONGO_URL=mongodb://root:123456@db-mongo:27017/Grucep23?authSource=admin
      # - DB_HOST=host.docker.internal

    expose:
      - 8080
    ports:
      - 8080:8080

volumes:
  mongodb:

    # docker compose -p grucep23 up -d
